# Generated by Django 4.2.17 on 2025-05-13 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_child_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedurl',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_blocked_urls', to='api.child'),
        ),
        migrations.AlterField(
            model_name='blockedurl',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_blocked_urls', to=settings.AUTH_USER_MODEL),
        ),
    ]
